<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
     <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
         <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>    

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\petrotec-opt-data\Petrotec.Opt.Data\Petrotec.Opt.Data.csproj" />
    <ProjectReference Include="..\petrotec-zorpay\Petrotec.ZorPay.Common\Petrotec.ZorPay.Common.csproj" />
    <ProjectReference Include="..\petrotec-zorpay\Petrotec.ZorPay\Petrotec.ZorPay.csproj" />
    <ProjectReference Include="..\petrotec-zorpay\petrotec-zorpay-opi-extension\Petrotec.ZorPay.Opi.Extension.csproj" />
  </ItemGroup>

</Project>
